# Generated by Django 5.1.2 on 2024-10-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="email",),
        migrations.RemoveField(model_name="profile", name="first_name",),
        migrations.RemoveField(model_name="profile", name="last_name",),
    ]
