# Generated by Django 5.1.2 on 2024-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_profile_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
